### ISSUE TITLE
How to Upload and display Photo?

### ISSUE THREAD

**Issue by cheahengsoon** [mjtpena/Xamarin-Training#1]
Hi Michael,

May I ask about how to Upload and Display Photo?
Any Sample?

Thank You.

**Comment by michaeljohnpena** [comment]
Hi, @cheahengsoon Thank you for your question.
Basically, in order to upload a picture you do the following:

1. Invoke a Picker to choose an image, this varies across different platforms. We use Media Plugin to do such functionality.
Refer to the following:
https://www.nuget.org/packages/Xam.Plugin.Media/
Good Documentation in here: 
https://blog.xamarin.com/getting-started-with-the-media-plugin-for-xamarin/

2. You will then have the image as part of Memory Stream.

3. Use that Stream to Display it Locally.

4. Upload that Stream to your Storage Provider. This might vary across different Providers such as Azure App Service, Azure Blob, ASP.NET Web API, Cognitive Services, etc.
Here is a good documentation on how to use Xamarin + Cognitive Services:
https://blog.xamarin.com/building-smart-apps-with-microsoft-cognitive-services/

5. Then if you need to display an image from an External source. It's just a straightforward setting the image control property "ImageSource" to display it. You can use the following for reference: https://github.com/michaeljohnpena/EnterpriseMobileAppDev/blob/master/02%20Dev-Labs%20PM/Finish/MyEvents/MyEvents/Views/SpeakersPage.xaml#L31

Best Regards,
Michael
